pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Étape de construction
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                // Étape de test
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                // Étape de déploiement
                sh 'mvn deploy'
            }
        }
        stage('Checkout') {
            steps {
                // Étape de vérification du code depuis le référentiel Git
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                // Étape pour exécuter Maven et lancer les tests
                sh 'mvn clean test'
            }
         }
    }
}
